[tool.poetry]
name = "abstractions"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
jax = "^0.4.8"
flax = "^0.6.8"
hydra-core = "^1.3.2"
loguru = "^0.6.0"
matplotlib = "^3.7.1"
numpy = "^1.24.2"
omegaconf = "^2.3.0"
optax = "^0.1.4"
pillow = "^9.5.0"
torchvision = "^0.15.1"
tqdm = "^4.65.0"
wandb = "^0.14.0"


[tool.poetry.group.dev.dependencies]
pytest = "^7.2.2"
black = "^23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
