[tool.poetry]
name = "abstractions"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
# Because we manually specify the jaxlib wheels to use, we need to fix the minor version
# of python
python = "~3.11"
flax = "^0.6.8"
hydra-core = "^1.3.2"
loguru = "^0.6.0"
matplotlib = "^3.7.1"
numpy = "^1.24.2"
omegaconf = "^2.3.0"
optax = "^0.1.4"
pillow = "^9.5.0"
torchvision = "^0.15.1"
tqdm = "^4.65.0"
wandb = "^0.14.0"
jax = "^0.4.7"
# The remaining dependencies are a hacky way to make this work both on linux and on mac.
# On linux, we want to install cuda support, on mac we don't.
# I haven't found a way to make this work automatically, the only thing I got working
# is to manually specify which wheels to use for jaxlib. (jax itself is the same either
# way). Then we also need to manually install the cuda dependencies because those
# would normally get installed via jax[cuda12-pip], not as jaxlib dependencies.
# Note this will currently fail on Intel macs because the wheel is for arm. It will
# also fail for any python versions but 3.11 (which is why we fix that earlier).
jaxlib = [
    {url = "https://storage.googleapis.com/jax-releases/cuda12/jaxlib-0.4.7+cuda12.cudnn88-cp311-cp311-manylinux2014_x86_64.whl", markers = "sys_platform == 'linux'"},
    {url = "https://storage.googleapis.com/jax-releases/mac/jaxlib-0.4.7-cp311-cp311-macosx_11_0_arm64.whl", markers = "sys_platform == 'darwin'"}
]

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.2"
black = "^23.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"