defaults:
  - _self_
  - optim: adam
  - model: mlp

num_epochs: 10
batch_size: 128
num_classes: 10
single_class: false
base_run: ???
debug: false
wandb: true

dir:
  log: logs/abstraction
  run: ${now:%Y-%m-%d_%H-%M-%S}
seed: 0
hydra:
  run:
    dir: ${dir.log}/${dir.run}
  job:
    chdir: true