defaults:
  - _self_
  - optim: adam

num_epochs: 10
batch_size: 128
abstract_dim: 256
model_path: ???
save_path: null
debug: false
wandb: true

dir:
  log: logs
  run: ${now:%Y-%m-%d_%H-%M-%S}
seed: 0
hydra:
  run:
    dir: ${dir.log}/${dir.run}