batch_size: 4096
max_batches: 0
rcond: 1e-5
relative: false
base_run: ???
anomaly: backdoor

dir:
  log: logs/mahalanobis
  run: ${now:%Y-%m-%d_%H-%M-%S}
seed: 0
hydra:
  run:
    dir: ${dir.log}/${dir.run}
  job:
    chdir: true