defaults:
  - _self_
  - optim: adam

num_epochs: 10
batch_size: 128
hidden_dim: 256
debug: false
wandb: true

dir:
  log: logs
  run: ${now:%Y-%m-%d_%H-%M-%S}
seed: 0
hydra:
  run:
    dir: ${dir.log}/${dir.run}
  job:
    chdir: true