defaults:
  - shared
  - optim: adam
  # Train data is a single dataset configuration. User needs to specify train_data.name
  # manually, e.g. train_data.name=mnist or +data@train_data=mnist.
  # To modify the train dataset, either use train_data.<property>=... or use config
  # groups like '+data@train_data=pixel_backdoor train_data.pixel_backdoor.p_backdoor=0.1'
  - data@train_data:
    - pytorch
    - train
  - _self_

num_epochs: 10
batch_size: 128
max_batch_size: 2048
num_classes: 10
max_steps: null
debug: false
wandb: false

