defaults:
  - shared
  # This is in fact non-optional but if I set it to ???, then I have to assign
  # directly to data@anomalies, instead of doing e.g. +data@anomalies.backdoor=...
  - data@anomalies: null
  - _self_
  # Disable all logging and cwd management.
  # The eval scripts write into the already existing run dir anyway
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# Path to log dir of the AnomalyDetector run
detector: ???
debug: false
adversarial: false
num_epochs: 1
normal_weight: 0.5
batch_size: 128
normal_batch_size: ${batch_size}
clip: true

hydra:
  job:
    chdir: false
  output_subdir: null
  run:
    dir: .
  sweep:
    dir: .
    subdir: .
